apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-model-task
spec:
  params:
    - name: git-repo
    - name: model-name
  results:
    - name: model-image
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone $(params.git-repo) /workspace/source
    
    - name: build-docker-image
      image: gcr.io/kaniko-project/executor:latest
      script: |
        /kaniko/executor --dockerfile=/workspace/source/Dockerfile \
                         --context=/workspace/source \
                         --destination=registry/$(params.model-name):$(date +%Y%m%d-%H%M%S) \
                         --cache=true
        echo "registry/$(params.model-name):$(date +%Y%m%d-%H%M%S)" > $(results.model-image.path)