apiVersion: v2
name: mlflow
version: 0.2.0
appVersion: "2.17.2"
description: A Helm chart for MLflow Tracking Server
type: application
keywords:
  - mlops
  - machine-learning
  - mlflow
  - tracking
maintainers:
  - name: ML Team
    email: contact@cnaas.link

dependencies:
  - name: common
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami
